name: bespoke · architecture
favicon: null
layout_spectrum: 0.23536
typography_spectrum: 0.48881
title: BESPOKE · ARCHITECTURE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#31241c'
    - '#dcd1bf'
    - '#685a4f'
    - '#b8ae9d'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.9177841637283564
purpose: []
