title: PANTHEON · ARCHITECTURE
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.75
  brandStrength: 0.6875
  rhythmicContrast: 0.25
  brandColors:
    - '#000000'
    - '#31241c'
    - '#dcd1bf'
    - '#685a4f'
    - '#b8ae9d'
  lightness: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: PANTHEON architecture
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9426644
layout_spectrum: 0.03878583
