name: BESPOKEARCHITECTURE
favicon: null
layout_spectrum: 0.57534
typography_spectrum: 0.48881
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#2b2b2b'
    - '#7c7b79'
    - '#c3c3c5'
  brandStrength: 0.125
  lightness: 0.8858511997386813
  saturation: 0.1875
  rhythmicContrast: 0.9177841637283564
purpose: []
